import pandas as pd
from dotenv import load_dotenv
from pathlib import Path
import os

class DataLoader:

    def __init__(self):
        load_dotenv()
        self.data_dir = os.getenv("DATA_DIR")

    def load_elaad_charging_profiles(self) -> pd.DataFrame:
        """
        Load all E-laad charging profiles. Assumes the folder_path contains only csv files generated by the E-laad
        LV profile generator. https://platform.elaad.io/analyse/low-voltage-charging-profiles/
        """
        folder_path = Path(self.data_dir, "elaad/laadprofielen")
        files_in_folder = os.listdir(folder_path)

        df = pd.DataFrame()
        last_run_id_ = 0

        for file_name in files_in_folder:

            df_file = pd.read_csv(Path(folder_path, file_name))
            df_file["run_id"] = df_file["run_id"] + last_run_id_

            df = pd.concat([df, df_file])
            last_run_id_ = df["run_id"].max()

        return df