import pandas as pd

from ev_detection.src.baseload_profiles import BaseloadProfiles
from ev_detection.src.charging_profile import ChargingProfiles

charging_profiles = ChargingProfiles()
baseload_profiles = BaseloadProfiles()

class SyntheticProfiles:

    def render_positives(self, n_profiles: int) -> list[pd.Series]:
        """
        Generate synthetic profiles by combining samples from PULSE baseload profiles with E-laad charging profiles.
        The profiles cover one week and the interval is 15 minutes and contain a charging profile.
        :param n_profiles: The number of profiles to generate
        :return: synthetic smart meter data
        """
        return [
            charging_sample + baseload_sample
            for charging_sample, baseload_sample in zip(
                charging_profiles.sample_weekly_profiles(n_profiles),
                baseload_profiles.sample_weekly_profiles(n_profiles)
            )
        ]

    def render_negatives(self, n_profiles: int) -> list[pd.Series]:
        """
        Generate synthetic profiles by sampling PULSE baseload profiles.
        The profiles cover one week and the interval is 15 minutes and do not contain a charging profile.
        :param n_profiles: The number of profiles to generate
        :return: synthetic smart meter data
        """
        return baseload_profiles.sample_weekly_profiles(n_profiles)

    def get_datetimes(self):
        """
        :return: timestamps for the profiles generated by self.render()
        """
        return charging_profiles.get_datetimes_week()